<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.6.2/tinymce.min.js"
    integrity="sha512-sOO7yng64iQzv/uLE8sCEhca7yet+D6vPGDEdXCqit1elBUAJD1jYIYqz0ov9HMd/k30e4UVFAovmSG92E995A=="
    crossorigin="anonymous"></script>

<script type="text/javascript">
    tinymce.init({
        selector: '.tinymce',
        language: '{{ config("app.locale") ?? "en" }}'
    });
</script>

<script>
    tinymce.addI18n('ca',{
        "Redo": "Refer",
        "Undo": "Desfer",
        "Cut": "Retalla",
        "Copy": "Copia",
        "Paste": "Enganxa",
        "Select all": "Seleccionar-ho tot",
        "New document": "Nou document",
        "Ok": "Acceptar",
        "Cancel": "Cancel\u00b7la",
        "Visual aids": "Assist\u00e8ncia visual",
        "Bold": "Negreta",
        "Italic": "Cursiva",
        "Underline": "Subratllat",
        "Strikethrough": "Barrat",
        "Superscript": "Super\u00edndex",
        "Subscript": "Sub\u00edndex",
        "Clear formatting": "Eliminar format",
        "Align left": "Alinea a l'esquerra",
        "Align center": "Alinea al centre",
        "Align right": "Alinea a la dreta",
        "Justify": "Justificat",
        "Bullet list": "Llista no ordenada",
        "Numbered list": "Llista enumerada",
        "Decrease indent": "Disminuir sagnat",
        "Increase indent": "Augmentar sagnat",
        "Close": "Tancar",
        "Formats": "Formats",
        "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.":
        "El vostre navegador no suporta l'acc\u00e9s directe al portaobjectes. Si us plau, feu servir les dreceres de teclat Ctrl+X\/C\/V.",
        "Headers": "Encap\u00e7alaments",
        "Header 1": "Encap\u00e7alament 1",
        "Header 2": "Encap\u00e7alament 2",
        "Header 3": "Encap\u00e7alament 3",
        "Header 4": "Encap\u00e7alament 4",
        "Header 5": "Encap\u00e7alament 5",
        "Header 6": "Encap\u00e7alament 6",
        "Headings": "Encap\u00e7alaments",
        "Heading 1": "Encap\u00e7alament 1",
        "Heading 2": "Encap\u00e7alament 2",
        "Heading 3": "Encap\u00e7alament 3",
        "Heading 4": "Encap\u00e7alament 4",
        "Heading 5": "Encap\u00e7alament 5",
        "Heading 6": "Encap\u00e7alament 6",
        "Preformatted": "Preformatat",
        "Div": "Div",
        "Pre": "Pre",
        "Code": "Codi",
        "Paragraph": "Par\u00e0graf",
        "Blockquote": "Cita",
        "Inline": "En l\u00ednia",
        "Blocks": "Blocs",
        "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":
        "Enganxar ara est\u00e0 en mode text pla. Els continguts s'enganxaran com a text pla fins que desactivis aquesta opci\u00f3. ",
        "Fonts": "Fonts",
        "Font Sizes": "Mides de la font",
        "Class": "Classe",
        "Browse for an image": "Explorar per cercar una imatge",
        "OR": "O",
        "Drop an image here": "Deixar anar una imatge aqu\u00ed",
        "Upload": "Pujar",
        "Block": "Bloc",
        "Align": "Alinea",
        "Default": "Per defecte",
        "Circle": "Cercle",
        "Disc": "Disc",
        "Square": "Quadrat",
        "Lower Alpha": "Alfa menor",
        "Lower Greek": "Grec menor",
        "Lower Roman": "Roman menor",
        "Upper Alpha": "Alfa major",
        "Upper Roman": "Roman major",
        "Anchor...": "Ancoratge...",
        "Name": "Nom",
        "Id": "Id",
        "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "La Id ha de comen\u00e7ar amb una lletra, seguida d'altres lletres, n\u00fameros, punts, ratlles, comes, o guions baixos",
        "You have unsaved changes are you sure you want to navigate away?": "Teniu canvis sense desar, esteu segur que voleu deixar-ho ara?",
        "Restore last draft": "Restaurar l'\u00faltim esborrany",
        "Special character...": "Car\u00e0cters especials\u2026",
        "Source code": "Codi font",
        "Insert\/Edit code sample": "Inserir\/Editar tros de codi",
        "Language": "Idioma",
        "Code sample...": "Mostra de codi...",
        "Color Picker": "Selector de colors",
        "R": "R",
        "G": "G",
        "B": "B",
        "Left to right": "D'esquerra a dreta",
        "Right to left": "De dreta a esquerra",
        "Emoticons...": "Emoticones...",
        "Metadata and Document Properties": "Metadades i propietats del document",
        "Title": "T\u00edtol",
        "Keywords": "Paraules clau",
        "Description": "Descripci\u00f3",
        "Robots": "Robots",
        "Author": "Autor",
        "Encoding": "Codificaci\u00f3",
        "Fullscreen": "Pantalla completa",
        "Action": "Acci\u00f3",
        "Shortcut": "Drecera",
        "Help": "Ajuda",
        "Address": "Adre\u00e7a",
        "Focus to menubar": "Enfocar la barra de men\u00fa",
        "Focus to toolbar": "Enfocar la barra d'eines",
        "Focus to element path": "Enfocar la ruta d'elements",
        "Focus to contextual toolbar": "Enfocar la barra d'eines contextual",
        "Insert link (if link plugin activated)": "Inserir enlla\u00e7 (si el complement d'enlla\u00e7 est\u00e0 activat)",
        "Save (if save plugin activated)": "Desar (si el complement desar est\u00e0 activat)",
        "Find (if searchreplace plugin activated)": "Cercar (si el complement cercar-reempla\u00e7ar est\u00e0 activat)",
        "Plugins installed ({0}):": "Complements instal\u00b7lats ({0}):",
        "Premium plugins:": "Complements premium",
        "Learn more...": "Apr\u00e8n m\u00e9s...",
        "You are using {0}": "Est\u00e0s utilitzant {0}",
        "Plugins": "Complements",
        "Handy Shortcuts": "Dreceres a m\u00e0",
        "Horizontal line": "L\u00ednia horitzontal",
        "Insert\/edit image": "Inserir\/editar imatge",
        "Image description": "Descripci\u00f3 de la imatge",
        "Source": "Font",
        "Dimensions": "Dimensions",
        "Constrain proportions": "Mantenir proporcions",
        "General": "General",
        "Advanced": "Avan\u00e7at",
        "Style": "Estil",
        "Vertical space": "Espai vertical",
        "Horizontal space": "Espai horitzontal",
        "Border": "Vora",
        "Insert image": "Inserir imatge",
        "Image...": "Imatge...",
        "Image list": "Llista d'imatges",
        "Rotate counterclockwise": "Girar a l'esquerra",
        "Rotate clockwise": "Girar a la dreta",
        "Flip vertically": "Capgirar verticalment",
        "Flip horizontally": "Capgirar horitzontalment",
        "Edit image": "Editar imatge",
        "Image options": "Opcions d'imatge",
        "Zoom in": "Ampliar",
        "Zoom out": "Empetitir",
        "Crop": "Escap\u00e7ar",
        "Resize": "Canviar mida",
        "Orientation": "Orientaci\u00f3",
        "Brightness": "Brillantor",
        "Sharpen": "Remarcar vores",
        "Contrast": "Contrast",
        "Color levels": "Nivells de color",
        "Gamma": "Gamma",
        "Invert": "Invertir",
        "Apply": "Aplicar",
        "Back": "Tornar",
        "Insert date\/time": "Inserir data\/hora",
        "Date\/time": "Data\/hora",
        "Insert\/Edit Link": "Inserir\/editar l'enlla\u00e7",
        "Insert\/edit link": "Inserir\/editar enlla\u00e7",
        "Text to display": "Text per mostrar",
        "Url": "URL",
        "Open link in...": "Obrir l'enlla\u00e7 a...",
        "Current window": "Finestra actual",
        "None": "Cap",
        "New window": "Finestra nova",
        "Remove link": "Treure enlla\u00e7",
        "Anchors": "\u00c0ncores",
        "Link...": "Enlla\u00e7...",
        "Paste or type a link": "Enganxa o escriu un enlla\u00e7",
        "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "L'URL que has escrit sembla una adre\u00e7a de correu electr\u00f2nic. Vols afegir-li el prefix obligatori mailto: ?",
        "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "L'URL que has escrit sembla un enlla\u00e7 extern. Vols afegir-li el prefix obligatori http:\/\/ ?",
        "Link list": "Llista d'enlla\u00e7os",
        "Insert video": "Inserir v\u00eddeo",
        "Insert\/edit video": "Inserir\/editar v\u00eddeo",
        "Insert\/edit media": "Inserir\/editar mitj\u00e0",
        "Alternative source": "Font alternativa",
        "Alternative source URL": "URL de font alternativa",
        "Media poster (Image URL)": "Cartell de multim\u00e8dia (URL d'imatge)",
        "Paste your embed code below:": "Enganxau el codi a sota:",
        "Embed": "Incloure",
        "Media...": "Multim\u00e8dia...",
        "Nonbreaking space": "Espai fixe",
        "Page break": "Salt de p\u00e0gina",
        "Paste as text": "Enganxar com a text",
        "Preview": "Previsualitzaci\u00f3",
        "Print...": "Imprimir...",
        "Save": "Desa",
        "Find": "Buscar",
        "Replace with": "Rempla\u00e7ar amb",
        "Replace": "Rempla\u00e7ar",
        "Replace all": "Rempla\u00e7ar-ho tot",
        "Previous": "Anterior",
        "Next": "Seg\u00fcent",
        "Find and replace...": "Cercar i reempla\u00e7ar...",
        "Could not find the specified string.": "No es pot trobar el text especificat.",
        "Match case": "Coincidir maj\u00fascules",
        "Find whole words only": "Cercar nom\u00e9s paraules completes",
        "Spell check": "Corrector ortogr\u00e0fic",
        "Ignore": "Ignorar",
        "Ignore all": "Ignorar tots",
        "Finish": "Finalitzar",
        "Add to Dictionary": "Afegir al diccionari",
        "Insert table": "Inserir taula",
        "Table properties": "Propietats de taula",
        "Delete table": "Esborrar taula",
        "Cell": "Cel\u00b7la",
        "Row": "Fila",
        "Column": "Columna",
        "Cell properties": "Propietats de cel\u00b7la",
        "Merge cells": "Fusionar cel\u00b7les",
        "Split cell": "Dividir cel\u00b7les",
        "Insert row before": "Inserir fila a sobre",
        "Insert row after": "Inserir fila a sota",
        "Delete row": "Esborrar fila",
        "Row properties": "Propietats de fila",
        "Cut row": "Retallar fila",
        "Copy row": "Copiar fila",
        "Paste row before": "Enganxar fila a sobre",
        "Paste row after": "Enganxar fila a sota",
        "Insert column before": "Inserir columna abans",
        "Insert column after": "Inserir columna despr\u00e9s",
        "Delete column": "Esborrar columna",
        "Cols": "Cols",
        "Rows": "Files",
        "Width": "Amplada",
        "Height": "Al\u00e7ada",
        "Cell spacing": "Espai entre cel\u00b7les",
        "Cell padding": "Marge intern",
        "Show caption": "Mostrar encap\u00e7alament",
        "Left": "A l'esquerra",
        "Center": "Centrat",
        "Right": "A la dreta",
        "Cell type": "Tipus de cel\u00b7la",
        "Scope": "\u00c0mbit",
        "Alignment": "Aliniament",
        "H Align": "Al\u00edniament H",
        "V Align": "Al\u00edniament V",
        "Top": "Superior",
        "Middle": "Mitj\u00e0",
        "Bottom": "Inferior",
        "Header cell": "Cel\u00b7la de cap\u00e7alera",
        "Row group": "Grup de fila",
        "Column group": "Grup de columna",
        "Row type": "Tipus de fila",
        "Header": "Cap\u00e7alera",
        "Body": "Cos",
        "Footer": "Peu",
        "Border color": "Color de vora",
        "Insert template...": "Inserir plantilla...",
        "Templates": "Plantilles",
        "Template": "Plantilla",
        "Text color": "Color del text",
        "Background color": "Color del fons",
        "Custom...": "Personalitzar...",
        "Custom color": "Personalitzar el color",
        "No color": "Sense color",
        "Remove color": "Eliminar el color",
        "Table of Contents": "Taula de continguts",
        "Show blocks": "Mostrar blocs",
        "Show invisible characters": "Mostrar car\u00e0cters invisibles",
        "Word count": "Recompte de paraules",
        "Count": "Compta",
        "Document": "Document",
        "Selection": "Selecci\u00f3",
        "Words": "Paraules",
        "Words: {0}": "Paraules: {0}",
        "{0} words": "{0} paraules",
        "File": "Arxiu",
        "Edit": "Edici\u00f3",
        "Insert": "Inserir",
        "View": "Veure",
        "Format": "Format",
        "Table": "Taula",
        "Tools": "Eines",
        "Powered by {0}": "Impulsat per {0}",
        "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "\u00c0rea de text amb format. Premeu ALT-F9 per mostrar el men\u00fa, ALT F10 per la barra d'eines i ALT-0 per ajuda.",
        "Image title": "T\u00edtol de la imatge",
        "Border width": "Amplada de la vora",
        "Border style": "Estil de la vora",
        "Error": "Error",
        "Warn": "Alerta",
        "Valid": "V\u00e0lid",
        "To open the popup, press Shift+Enter": "Per obrir la finestra emergent, premeu Maj.+Retorn",
        "Rich Text Area. Press ALT-0 for help.": "\u00c0rea de Text enriquit. Premeu ALT-0 per obtenir ajuda.",
        "System Font": "Font del sistema",
        "Failed to upload image: {0}": "No s'ha pogut carregar la imatge: {0}",
        "Failed to load plugin: {0} from url {1}": "No s'ha pogut carregar el complement: {0} de l\u2019URL {1}",
        "Failed to load plugin url: {0}": "No s'ha pogut carregar l\u2019URL del complement: {0}",
        "Failed to initialize plugin: {0}": "No s'ha pogut inicialitzar el complement: {0}",
        "example": "exemple",
        "Search": "Cerca",
        "All": "Tot",
        "Currency": "Moneda",
        "Text": "Text",
        "Quotations": "Cites",
        "Mathematical": "S\u00edmbols matem\u00e0tics",
        "Extended Latin": "Llat\u00ed ampliat",
        "Symbols": "S\u00edmbols",
        "Arrows": "Fletxes",
        "User Defined": "Definit per l'usuari",
        "dollar sign": "signe del d\u00f2lar",
        "currency sign": "signe de la moneda",
        "euro-currency sign": "signe de l'euro",
        "colon sign": "signe del col\u00f3n",
        "cruzeiro sign": "signe del cruzeiro",
        "french franc sign": "signe del franc franc\u00e8s",
        "lira sign": "signe de la lira",
        "mill sign": "signe del mill",
        "naira sign": "signe de la naira",
        "peseta sign": "signe de la pesseta",
        "rupee sign": "signe de la rupia",
        "won sign": "signe del won",
        "new sheqel sign": "signe del nou x\u00e9quel",
        "dong sign": "signe del dong",
        "kip sign": "signe del kip",
        "tugrik sign": "signe del t\u00f6gr\u00f6g",
        "drachma sign": "signe del dracma",
        "german penny symbol": "signe del penic alemany",
        "peso sign": "signe del peso",
        "guarani sign": "signe del guaran\u00ed",
        "austral sign": "signe de l\u2019austral",
        "hryvnia sign": "signe de la hr\u00edvnia",
        "cedi sign": "signe del cedi",
        "livre tournois sign": "signe de la lliura tornesa",
        "spesmilo sign": "signe de l\u2019spesmilo",
        "tenge sign": "signe del tenge",
        "indian rupee sign": "signe de la rupia \u00edndia",
        "turkish lira sign": "signe de la lira turca",
        "nordic mark sign": "signe del marc n\u00f2rdic",
        "manat sign": "signe del manat",
        "ruble sign": "signe del ruble",
        "yen character": "signe del ien",
        "yuan character": "signe del iuan",
        "yuan character, in hong kong and taiwan": "signe del iuan en Hong Kong i Taiwan",
        "yen\/yuan character variant one": "variaci\u00f3 1 del signe del ien\/iuan",
        "Loading emoticons...": "Carregant les emoticones...",
        "Could not load emoticons": "No s'han pogut carregar les emoticones",
        "People": "Gent",
        "Animals and Nature": "Animals i natura",
        "Food and Drink": "Menjar i beure",
        "Activity": "Activitat",
        "Travel and Places": "Viatges i llocs",
        "Objects": "Objectes",
        "Flags": "Banderes",
        "Characters": "Car\u00e0cters",
        "Characters (no spaces)": "Car\u00e0cters (sense espais)",
        "{0} characters": "{0} car\u00e0cters",
        "Error: Form submit field collision.": "Error: error en el camp d\u2019enviament del formulari.",
        "Error: No form element found.": "Error: no s'ha trobat l'element del formulari.",
        "Update": "Actualitzar",
        "Color swatch": "Mostra de color",
        "Turquoise": "Turquesa",
        "Green": "Verd",
        "Blue": "Blau",
        "Purple": "Violeta",
        "Navy Blue": "Blau mar\u00ed",
        "Dark Turquoise": "Turquesa fosc",
        "Dark Green": "Verd fosc",
        "Medium Blue": "Blau mitj\u00e0",
        "Medium Purple": "Violeta mitj\u00e0",
        "Midnight Blue": "Blau mitjanit",
        "Yellow": "Groc",
        "Orange": "Taronja",
        "Red": "Vermell",
        "Light Gray": "Gris clar",
        "Gray": "Gris",
        "Dark Yellow": "Groc fosc",
        "Dark Orange": "Taronja fosc",
        "Dark Red": "Vermell fosc",
        "Medium Gray": "Gris mitj\u00e0",
        "Dark Gray": "Gris fosc",
        "Light Green": "Verd clar",
        "Light Yellow": "Groc clar",
        "Light Red": "Vermell clar",
        "Light Purple": "Porpra clar",
        "Light Blue": "Blau clar",
        "Dark Purple": "Porpra fosc",
        "Dark Blue": "Blau fosc",
        "Black": "Negre",
        "White": "Blanc",
        "Switch to or from fullscreen mode": "Canviar a o del mode de pantalla completa",
        "Open help dialog": "Obrir el quadre de di\u00e0leg d'ajuda",
        "history": "historial",
        "styles": "estils",
        "formatting": "format",
        "alignment": "alineaci\u00f3",
        "indentation": "sagnat",
        "permanent pen": "retolador permanent",
        "comments": "comentaris",
        "Format Painter": "Formata el Painter",
        "Insert\/edit iframe": "Insereix\/edita iframe",
        "Capitalization": "Capitalitzaci\u00f3",
        "lowercase": "min\u00fascules",
        "UPPERCASE": "MAJ\u00daSCULES",
        "Title Case": "Caixa del t\u00edtol",
        "Permanent Pen Properties": "Par\u00e0metres permanents del llapis",
        "Permanent pen properties...": "Par\u00e0metres permanents del llapis\u2026",
        "Font": "Font",
        "Size": "Mida",
        "More...": "M\u00e9s\u2026",
        "Spellcheck Language": "Idioma de la comprovaci\u00f3 d'ortografia",
        "Select...": "Selecciona\u2026",
        "Preferences": "Par\u00e0metres",
        "Yes": "S\u00ed",
        "No": "No",
        "Keyboard Navigation": "Navegaci\u00f3 per teclat",
        "Version": "Versi\u00f3",
        "Anchor": "\u00c0ncora",
        "Special character": "Car\u00e0cter especial",
        "Code sample": "Mostra de codi",
        "Color": "Color",
        "Emoticons": "Emoticones",
        "Document properties": "Propietats del document",
        "Image": "Imatge",
        "Insert link": "Inserir enlla\u00e7",
        "Target": "Dest\u00ed",
        "Link": "Enlla\u00e7",
        "Poster": "P\u00f3ster",
        "Media": "Mitjans",
        "Print": "Imprimir",
        "Prev": "Anterior",
        "Find and replace": "Buscar i rempla\u00e7ar",
        "Whole words": "Paraules senceres",
        "Spellcheck": "Comprovar ortrografia",
        "Caption": "Encap\u00e7alament",
        "Insert template": "Inserir plantilla"
    });

    tinymce.addI18n('es',{
        "Redo": "Rehacer",
        "Undo": "Deshacer",
        "Cut": "Cortar",
        "Copy": "Copiar",
        "Paste": "Pegar",
        "Select all": "Seleccionar todo",
        "New document": "Nuevo documento",
        "Ok": "Ok",
        "Cancel": "Cancelar",
        "Visual aids": "Ayudas visuales",
        "Bold": "Negrita",
        "Italic": "Cursiva",
        "Underline": "Subrayado",
        "Strikethrough": "Tachado",
        "Superscript": "Super\u00edndice",
        "Subscript": "Sub\u00edndice",
        "Clear formatting": "Limpiar formato",
        "Align left": "Alinear a la izquierda",
        "Align center": "Alinear al centro",
        "Align right": "Alinear a la derecha",
        "Justify": "Justificar",
        "Bullet list": "Lista de vi\u00f1etas",
        "Numbered list": "Lista numerada",
        "Decrease indent": "Disminuir sangr\u00eda",
        "Increase indent": "Incrementar sangr\u00eda",
        "Close": "Cerrar",
        "Formats": "Formatos",
        "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.":
        "Su navegador no es compatible con el acceso directo al portapapeles. Use las teclas Crtl+X\/C\/V de su teclado.",
        "Headers": "Encabezados",
        "Header 1": "Encabezado 1",
        "Header 2": "Encabezado 2",
        "Header 3": "Encabezado 3",
        "Header 4": "Encabezado 4",
        "Header 5": "Encabezado 5",
        "Header 6": "Encabezado 6",
        "Headings": "Encabezados",
        "Heading 1": "Encabezado 1",
        "Heading 2": "Encabezado 2",
        "Heading 3": "Encabezado 3",
        "Heading 4": "Encabezado 4",
        "Heading 5": "Encabezado 5",
        "Heading 6": "Encabezado 6",
        "Preformatted": "Con formato previo",
        "Div": "Div",
        "Pre": "Pre",
        "Code": "C\u00f3digo",
        "Paragraph": "P\u00e1rrafo",
        "Blockquote": "Blockquote",
        "Inline": "Alineado",
        "Blocks": "Bloques",
        "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Pegar est\u00e1 ahora en modo de texto plano. El contenido se pegar\u00e1 como texto plano hasta que desactive esta opci\u00f3n.",
        "Fonts": "Fuentes",
        "Font Sizes": "Tama\u00f1os de fuente",
        "Class": "Clase",
        "Browse for an image": "Buscar una imagen",
        "OR": "OR",
        "Drop an image here": "Arrastre una imagen aqu\u00ed",
        "Upload": "Cargar",
        "Block": "Bloque",
        "Align": "Alinear",
        "Default": "Por defecto",
        "Circle": "C\u00edrculo",
        "Disc": "Disco",
        "Square": "Cuadrado",
        "Lower Alpha": "Inferior Alfa",
        "Lower Greek": "Inferior Griega",
        "Lower Roman": "Inferior Romana",
        "Upper Alpha": "Superior Alfa",
        "Upper Roman": "Superior Romana",
        "Anchor...": "Anclaje...",
        "Name": "Nombre",
        "Id": "Id",
        "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Deber\u00eda comenzar por una letra, seguida solo de letras, n\u00fameros, guiones, puntos, dos puntos o guiones bajos.",
        "You have unsaved changes are you sure you want to navigate away?": "Tiene cambios sin guardar. \u00bfEst\u00e1 seguro de que quiere salir?",
        "Restore last draft": "Restaurar el \u00faltimo borrador",
        "Special character...": "Car\u00e1cter especial...",
        "Source code": "C\u00f3digo fuente",
        "Insert\/Edit code sample": "Insertar\/editar c\u00f3digo de prueba",
        "Language": "Idioma",
        "Code sample...": "Ejemplo de c\u00f3digo...",
        "Color Picker": "Selector de colores",
        "R": "R",
        "G": "V",
        "B": "A",
        "Left to right": "De izquierda a derecha",
        "Right to left": "De derecha a izquierda",
        "Emoticons...": "Emoticones...",
        "Metadata and Document Properties": "Metadatos y propiedades del documento",
        "Title": "T\u00edtulo",
        "Keywords": "Palabras clave",
        "Description": "Descripci\u00f3n",
        "Robots": "Robots",
        "Author": "Autor",
        "Encoding": "Codificaci\u00f3n",
        "Fullscreen": "Pantalla completa",
        "Action": "Acci\u00f3n",
        "Shortcut": "Atajo",
        "Help": "Ayuda",
        "Address": "Direcci\u00f3n",
        "Focus to menubar": "Enfocar la barra del men\u00fa",
        "Focus to toolbar": "Enfocar la barra de herramientas",
        "Focus to element path": "Enfocar la ruta del elemento",
        "Focus to contextual toolbar": "Enfocar la barra de herramientas contextual",
        "Insert link (if link plugin activated)": "Insertar enlace (si el complemento de enlace est\u00e1 activado)",
        "Save (if save plugin activated)": "Guardar (si el componente de salvar est\u00e1 activado)",
        "Find (if searchreplace plugin activated)": "Buscar (si el complemento buscar-remplazar est\u00e1 activado)",
        "Plugins installed ({0}):": "Plugins instalados ({0}):",
        "Premium plugins:": "Complementos premium:",
        "Learn more...": "Aprende m\u00e1s...",
        "You are using {0}": "Estas usando {0}",
        "Plugins": "Complementos",
        "Handy Shortcuts": "Accesos directos",
        "Horizontal line": "L\u00ednea horizontal",
        "Insert\/edit image": "Insertar\/editar imagen",
        "Image description": "Descripci\u00f3n de la imagen",
        "Source": "Enlace",
        "Dimensions": "Dimensiones",
        "Constrain proportions": "Restringir proporciones",
        "General": "General",
        "Advanced": "Avanzado",
        "Style": "Estilo",
        "Vertical space": "Espacio vertical",
        "Horizontal space": "Espacio horizontal",
        "Border": "Borde",
        "Insert image": "Insertar imagen",
        "Image...": "Imagen...",
        "Image list": "Lista de im\u00e1genes",
        "Rotate counterclockwise": "Girar a la izquierda",
        "Rotate clockwise": "Girar a la derecha",
        "Flip vertically": "Invertir verticalmente",
        "Flip horizontally": "Invertir horizontalmente",
        "Edit image": "Editar imagen",
        "Image options": "Opciones de imagen",
        "Zoom in": "Acercar",
        "Zoom out": "Alejar",
        "Crop": "Recortar",
        "Resize": "Redimensionar",
        "Orientation": "Orientaci\u00f3n",
        "Brightness": "Brillo",
        "Sharpen": "Forma",
        "Contrast": "Contraste",
        "Color levels": "Niveles de color",
        "Gamma": "Gamma",
        "Invert": "Invertir",
        "Apply": "Aplicar",
        "Back": "Atr\u00e1s",
        "Insert date\/time": "Insertar fecha\/hora",
        "Date\/time": "Fecha\/hora",
        "Insert\/Edit Link": "Insertar\/editar enlace",
        "Insert\/edit link": "Insertar\/editar enlace",
        "Text to display": "Texto para mostrar",
        "Url": "URL",
        "Open link in...": "Abrir enlace en...",
        "Current window": "Ventana actual",
        "None": "Ninguno",
        "New window": "Nueva ventana",
        "Remove link": "Quitar enlace",
        "Anchors": "Anclas",
        "Link...": "Enlace...",
        "Paste or type a link": "Pega o introduce un enlace",
        "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "El enlace que has introducido no parece ser una direcci\u00f3n de correo electr\u00f3nico. Quieres a\u00f1adir el prefijo necesario mailto: ?",
        "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "El enlace que has introducido no parece ser una enlace externo. Quieres a\u00f1adir el prefijo necesario http:\/\/ ?",
        "Link list": "Lista de enlaces",
        "Insert video": "Insertar video",
        "Insert\/edit video": "Insertar\/editar video",
        "Insert\/edit media": "Insertar\/editar medio",
        "Alternative source": "Enlace alternativo",
        "Alternative source URL": "Origen de URL alternativo",
        "Media poster (Image URL)": "P\u00f3ster de medio (URL de imagen)",
        "Paste your embed code below:": "Pega tu c\u00f3digo embebido debajo",
        "Embed": "Incrustado",
        "Media...": "Medios...",
        "Nonbreaking space": "Espacio fijo",
        "Page break": "Salto de p\u00e1gina",
        "Paste as text": "Pegar como texto",
        "Preview": "Previsualizar",
        "Print...": "Imprimir...",
        "Save": "Guardar",
        "Find": "Buscar",
        "Replace with": "Reemplazar con",
        "Replace": "Reemplazar",
        "Replace all": "Reemplazar todo",
        "Previous": "Anterior",
        "Next": "Siguiente",
        "Find and replace...": "Buscar y reemplazar...",
        "Could not find the specified string.": "No se encuentra la cadena de texto especificada",
        "Match case": "Coincidencia exacta",
        "Find whole words only": "Solo palabras completas",
        "Spell check": "Revisar ortograf\u00eda",
        "Ignore": "Ignorar",
        "Ignore all": "Ignorar todos",
        "Finish": "Finalizar",
        "Add to Dictionary": "A\u00f1adir al Diccionario",
        "Insert table": "Insertar tabla",
        "Table properties": "Propiedades de la tabla",
        "Delete table": "Eliminar tabla",
        "Cell": "Celda",
        "Row": "Fila",
        "Column": "Columna",
        "Cell properties": "Propiedades de la celda",
        "Merge cells": "Combinar celdas",
        "Split cell": "Dividir celdas",
        "Insert row before": "Insertar fila antes",
        "Insert row after": "Insertar fila despu\u00e9s ",
        "Delete row": "Eliminar fila",
        "Row properties": "Propiedades de la fila",
        "Cut row": "Cortar fila",
        "Copy row": "Copiar fila",
        "Paste row before": "Pegar la fila antes",
        "Paste row after": "Pegar la fila despu\u00e9s",
        "Insert column before": "Insertar columna antes",
        "Insert column after": "Insertar columna despu\u00e9s",
        "Delete column": "Eliminar columna",
        "Cols": "Columnas",
        "Rows": "Filas",
        "Width": "Ancho",
        "Height": "Alto",
        "Cell spacing": "Espacio entre celdas",
        "Cell padding": "Relleno de celda",
        "Show caption": "Mostrar t\u00edtulo",
        "Left": "Izquierda",
        "Center": "Centrado",
        "Right": "Derecha",
        "Cell type": "Tipo de celda",
        "Scope": "\u00c1mbito",
        "Alignment": "Alineaci\u00f3n",
        "H Align": "Alineamiento Horizontal",
        "V Align": "Alineamiento Vertical",
        "Top": "Arriba",
        "Middle": "Centro",
        "Bottom": "Abajo",
        "Header cell": "Celda de la cebecera",
        "Row group": "Grupo de filas",
        "Column group": "Grupo de columnas",
        "Row type": "Tipo de fila",
        "Header": "Cabecera",
        "Body": "Cuerpo",
        "Footer": "Pie de p\u00e1gina",
        "Border color": "Color del borde",
        "Insert template...": "Insertar plantilla...",
        "Templates": "Plantillas",
        "Template": "Plantilla",
        "Text color": "Color del texto",
        "Background color": "Color de fondo",
        "Custom...": "Personalizar...",
        "Custom color": "Color personalizado",
        "No color": "Sin color",
        "Remove color": "Quitar color",
        "Table of Contents": "Tabla de contenidos",
        "Show blocks": "Mostrar bloques",
        "Show invisible characters": "Mostrar caracteres invisibles",
        "Word count": "Contar palabras",
        "Count": "Recuento",
        "Document": "Documento",
        "Selection": "Selecci\u00f3n",
        "Words": "Palabras",
        "Words: {0}": "Palabras: {0}",
        "{0} words": "{0} palabras",
        "File": "Archivo",
        "Edit": "Editar",
        "Insert": "Insertar",
        "View": "Ver",
        "Format": "Formato",
        "Table": "Tabla",
        "Tools": "Herramientas",
        "Powered by {0}": "Desarrollado por {0}",
        "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "\u00c1rea de texto enriquecido. Pulse ALT-F9 para el menu. Pulse ALT-F10 para la barra de herramientas. Pulse ALT-0 para ayuda",
        "Image title": "Titulo de imagen",
        "Border width": "Ancho de borde",
        "Border style": "Estilo de borde",
        "Error": "Error",
        "Warn": "Advertencia",
        "Valid": "V\u00e1lido",
        "To open the popup, press Shift+Enter": "Para abrir el elemento emergente, pulse May\u00fas+Intro",
        "Rich Text Area. Press ALT-0 for help.": "\u00c1rea de texto enriquecido. Pulse ALT-0 para abrir la ayuda.",
        "System Font": "Fuente de sistema",
        "Failed to upload image: {0}": "Fallo al cargar imagen: {0}",
        "Failed to load plugin: {0} from url {1}": "Fallo al cargar complemento: {0} desde URL {1}",
        "Failed to load plugin url: {0}": "Fallo al cargar URL del complemento: {0}",
        "Failed to initialize plugin: {0}": "Fallo al iniciar el complemento: {0}",
        "example": "ejemplo",
        "Search": "Buscar",
        "All": "Todo",
        "Currency": "Divisa",
        "Text": "Texto",
        "Quotations": "Comillas",
        "Mathematical": "S\u00edmbolo matem\u00e1tico",
        "Extended Latin": "Latino extendido A",
        "Symbols": "S\u00edmbolos",
        "Arrows": "Flechas",
        "User Defined": "Definido por el usuario",
        "dollar sign": "signo de d\u00f3lar",
        "currency sign": "signo de divisa",
        "euro-currency sign": "signo de euro",
        "colon sign": "signo de dos puntos",
        "cruzeiro sign": "signo de cruceiro",
        "french franc sign": "signo de franco franc\u00e9s",
        "lira sign": "signo de lira",
        "mill sign": "signo de mill",
        "naira sign": "signo de naira",
        "peseta sign": "signo de peseta",
        "rupee sign": "signo de rupia",
        "won sign": "signo de won",
        "new sheqel sign": "signo de nuevo s\u00e9quel",
        "dong sign": "signo de dong",
        "kip sign": "signo de kip",
        "tugrik sign": "signo de tugrik",
        "drachma sign": "signo de dracma",
        "german penny symbol": "signo de penique alem\u00e1n",
        "peso sign": "signo de peso",
        "guarani sign": "signo de guaran\u00ed",
        "austral sign": "signo de austral",
        "hryvnia sign": "signo de grivna",
        "cedi sign": "signo de cedi",
        "livre tournois sign": "signo de libra tornesa",
        "spesmilo sign": "signo de spesmilo",
        "tenge sign": "signo de tenge",
        "indian rupee sign": "signo de rupia india",
        "turkish lira sign": "signo de lira turca",
        "nordic mark sign": "signo de marco n\u00f3rdico",
        "manat sign": "signo de manat",
        "ruble sign": "signo de rublo",
        "yen character": "car\u00e1cter de yen",
        "yuan character": "car\u00e1cter de yuan",
        "yuan character, in hong kong and taiwan": "car\u00e1cter de yuan en Hong Kong y Taiw\u00e1n",
        "yen\/yuan character variant one": "Variante uno de car\u00e1cter de yen\/yuan",
        "Loading emoticons...": "Cargando emoticonos...",
        "Could not load emoticons": "No se han podido cargar los emoticonos",
        "People": "Personas",
        "Animals and Nature": "Animales y naturaleza",
        "Food and Drink": "Comida y bebida",
        "Activity": "Actividad",
        "Travel and Places": "Viajes y lugares",
        "Objects": "Objetos",
        "Flags": "Banderas",
        "Characters": "Caracteres",
        "Characters (no spaces)": "Caracteres (sin espacios)",
        "{0} characters": "{0} caracteres",
        "Error: Form submit field collision.": "Error: Colisi\u00f3n de campo al enviar formulario.",
        "Error: No form element found.": "Error: No se encuentra ning\u00fan elemento de formulario.",
        "Update": "Actualizar",
        "Color swatch": "Muestrario de colores",
        "Turquoise": "Turquesa",
        "Green": "Verde",
        "Blue": "Azul",
        "Purple": "P\u00farpura",
        "Navy Blue": "Azul marino",
        "Dark Turquoise": "Turquesa oscuro",
        "Dark Green": "Verde oscuro",
        "Medium Blue": "Azul medio",
        "Medium Purple": "P\u00farpura medio",
        "Midnight Blue": "Azul medio",
        "Yellow": "Amarillo",
        "Orange": "Naranja",
        "Red": "Rojo",
        "Light Gray": "Gris claro",
        "Gray": "Gris",
        "Dark Yellow": "Amarillo oscuro",
        "Dark Orange": "Naranja oscuro",
        "Dark Red": "Rojo oscuro",
        "Medium Gray": "Gris medio",
        "Dark Gray": "Gris oscuro",
        "Light Green": "Verde claro",
        "Light Yellow": "Amarillo claro",
        "Light Red": "Rojo claro",
        "Light Purple": "Morado claro",
        "Light Blue": "Azul claro",
        "Dark Purple": "Morado oscuro",
        "Dark Blue": "Azul oscuro",
        "Black": "Negro",
        "White": "Blanco",
        "Switch to or from fullscreen mode": "Activar o desactivar modo pantalla completa",
        "Open help dialog": "Abrir di\u00e1logo de ayuda",
        "history": "historial",
        "styles": "estilos",
        "formatting": "formato",
        "alignment": "alineaci\u00f3n",
        "indentation": "sangr\u00eda",
        "permanent pen": "bol\u00edgrafo permanente",
        "comments": "comentarios",
        "Format Painter": "Copiar formato",
        "Insert\/edit iframe": "Insertar\/editar iframe",
        "Capitalization": "Uso de may\u00fasculas",
        "lowercase": "min\u00fasculas",
        "UPPERCASE": "MAY\u00daSCULAS",
        "Title Case": "Tipo T\u00edtulo",
        "Permanent Pen Properties": "Propiedades del bol\u00edgrafo permanente",
        "Permanent pen properties...": "Propiedades del bol\u00edgrafo permanente...",
        "Font": "Fuente",
        "Size": "Tama\u00f1o",
        "More...": "M\u00e1s...",
        "Spellcheck Language": "Corrector",
        "Select...": "Seleccionar...",
        "Preferences": "Preferencias",
        "Yes": "S\u00ed",
        "No": "No",
        "Keyboard Navigation": "Navegaci\u00f3n con el teclado",
        "Version": "Versi\u00f3n",
        "Anchor": "Ancla",
        "Special character": "Car\u00e1cter especial",
        "Code sample": "Ejemplo de c\u00f3digo",
        "Color": "Color",
        "Emoticons": "Emoticonos",
        "Document properties": "Propiedades del documento",
        "Image": "Imagen",
        "Insert link": "Insertar enlace",
        "Target": "Destino",
        "Link": "Enlace",
        "Poster": "Miniatura",
        "Media": "Media",
        "Print": "Imprimir",
        "Prev": "Anterior",
        "Find and replace": "Buscar y reemplazar",
        "Whole words": "Palabras completas",
        "Spellcheck": "Corrector ortogr\u00e1fico",
        "Caption": "Subt\u00edtulo",
        "Insert template": "Insertar plantilla"
    });
</script>
